### ISSUE TITLE
Finding a specific Winery, vineyard, tasting room

### ISSUE THREAD

**Issue by fmichaelconway** [azgs/azwinemap#10]
Jessica: Can we build a simple search tool that allows the viewer to search by name for a winery? For instance, Grand Canyon Wine Co.  Or can we include a pop up list or index with all participating groups that is interactive and links to their description?

Currently, if you want to find someone in the Verde valley, you have to go through the icons one at a time until the one you want pops up.
Or am I missing something?
Mike

**Comment by jessicagood** [comment]
@fmichaelconway Instead of a search tool I added a list of all locations currently on the map. As you add filters or pan around the map this list automatically updates. Clicking on an item in the list will take you to its details page. Will this work?

**Comment by fmichaelconway** [comment]
Looks great! Thanks.
