### ISSUE TITLE
Directions - Highlighting active Directions button

### ISSUE THREAD

**Issue by fmichaelconway** [azgs/azwinemap#12]
I think there may some confusion with directions at the wine map. Once a vineyard is selected and the info pop ups, could we color the active Directions box green to indicate that it is the most appropriate choice.  I mocked it up here.  M

![directions](https://cloud.githubusercontent.com/assets/5924192/10463350/f93031f4-7198-11e5-87e7-c16b67704908.png)

**Comment by jessicagood** [comment]
@fmichaelconway Done
