### ISSUE TITLE
Help with map?

### ISSUE THREAD

**Issue by skmar** [azgs/azwinemap#13]
@jessica-azgs, can you help me with some of the edits on the map? 

I've added a horizontal rule and a header for winery list, but this caused a scroll bar along the whole sidebar area (not just along the list of wineries). I'm not sure what I can do to prevent the scroll along the whole sidebar. If I take out the header and the horizontal rule it does not push everything down to create a scroll bar but I would like to have these components. Can you help/direct me to what I can do to fix this?

Attached screenshot of what I'm talking about. 
![winemap-new-icon](https://cloud.githubusercontent.com/assets/6004822/10615965/90d07dba-7717-11e5-9423-65e3f4803b5b.PNG)

Thanks,
Stephanie

**Comment by jessicagood** [comment]
@skmar I had trouble with that big scroll bar too. It still shows up sometimes on the live site depending on screen size and yeah, it looks terrible when it appears. You might have seen this already but the css for this is set in the javascript [here](https://github.com/azgs/azwinemap/blob/master/scripts/app.js#L74). Not sure that if that helps much though.

**Comment by skmar** [comment]
Thanks, it does help. I do remember you defined some aspects in javascript but I since I know very little about javascript I was reluctant to muck around there. But I edited the height and got the extra scroll bar to go away.
