### ISSUE TITLE
Edits to wine map

### ISSUE THREAD

**Issue by skmar** [azgs/azwinemap#15]
Hi @Lbookman and @jessica-azgs,

I've made a few edits to the wine map that we want to see how they turn out on mobile devices. The testing I've done on my browser have not been great but we want to see how it looks on a actual mobile device. Is there a way we can do this? I have the files, but I can not upload the zip here, what would be the best way for me to get you the files?

Thanks,
Stephanie 
@fmichaelconway, @ridavis

**Comment by jessicagood** [comment]
@skmar Have you spoofed mobile devices in Chrome to see how it looks already? That's in the Developer tools - you can change the viewing platform to multiple phones and tablets. If so and that looks fine let me know and I'll come over to help you upload the changes.

**Comment by skmar** [comment]
Hi @jessica-azgs 

I'm hoping to get the version of the map I've been working before tomorrow. Do you have time today to show me how to push the changes?

**Comment by jessicagood** [comment]
@skmar Sure, I'll stop by this afternoon. Let me know if there is a particular time that is bad.

**Comment by skmar** [comment]
@jessica-azgs Anytime works for me. Thanks. :)
