### ISSUE TITLE
Title too long

### ISSUE THREAD

**Issue by jessicagood** [azgs/azwinemap#16]
@skmar We need to change the title to 'Arizona Wine' or something else fairly short like that so that the text does not spill onto another line when viewed on a phone. It does this even now with the current live site because 'Vineyards, Wineries and Tasting Rooms of Arizona' is too long. It takes up too much real estate on the phone when it spills to another line and it covers up the menu button.

**Comment by skmar** [comment]
Oh, I think 'Arizona Wine' is good for me. @fmichaelconway and @ridavis does that work for you?

**Comment by ridavis** [comment]
I like Arizona Wine or Arizona Wine Map, thanks!

**Comment by fmichaelconway** [comment]
Something more specific maybe - Arizona Wine Country Map

**Comment by fmichaelconway** [comment]
Whoops make it trails not country. M

**Comment by skmar** [comment]
"AZ Wine Map" seems like the only thing that will work with the icons.

**Comment by fmichaelconway** [comment]
Sound like AZ Wine Map might be the ticket.
M

**Comment by skmar** [comment]
This does not work on screens smaller than 300px.I'm not sure what are the statistics of screens smaller than 300px.

**Comment by fmichaelconway** [comment]
If it fits the inphone and most androids, we are probably good. 
M

**Comment by skmar** [comment]
Fixed with commit 40519e4
