### ISSUE TITLE
Add location feature for single entries

### ISSUE THREAD

**Issue by ridavis** [azgs/azwinemap#6]
Is it possible to add a location without creating an additional account? What if the people want to display their tasting room and winery at their vineyard, but also have a tasting room in downtown Tucson? Assuming the products they offer are the same, is there a way to make it so one entry could display multiple points?

**Comment by ridavis** [comment]
From Mike: 
The flying leap vineyard has two vineyards and 4  tasting rooms. The template does not appear to self-populate, so the same info – name, hrs, e-mail, website … has to be entered 6 times. Is there a way to make the individual sheets of a single account  self populate?

 How much work will this take? Is adding a self-population feature worth it?

**Comment by jessicagood** [comment]
This is for entering data so actually should be in https://github.com/azgs/azwine/issues instead. I'll have to look into this more next week but I think it would take a day or so. It brings up the question though if a business does have multiple locations with varying differences in values how would we know which to use as default values if a new location is entered?

**Comment by jessicagood** [comment]
@ridavis @fmichaelconway I don't see an easy way to do this. It's not super important is it?

**Comment by ridavis** [comment]
nope.

**Comment by fmichaelconway** [comment]
The data is now in place so it is unnecessary. M
