### ISSUE TITLE
Open Now feature

### ISSUE THREAD

**Issue by ridavis** [azgs/azwinemap#7]
Is it possible to create a feature where there is an option to view only wineries that are open in real time? How much effort would that take?

**Comment by jessicagood** [comment]
@ridavis This would be a nice feature. A little bit of work but doable. I'll take a look at it.

**Comment by jessicagood** [comment]
@ridavis I've updated the site with an open now button. Let me know if this is what you wanted.

**Comment by ridavis** [comment]
yup, that is awesome.
