### ISSUE TITLE
Populating winemap - ETA Tuesday 13 Oct - Adding icons

### ISSUE THREAD

**Issue by fmichaelconway** [azgs/azwinemap#8]
Jessica | Laura: We will have all, or nearly all, of AZ wine folks on the map by next Tuesday.
When will you be able to add icons:
Wine bottle – tipped to indicate multiple feature (winery and/or vineyard and/or tasting room) 
Wine glass – Tasting Room
Vineyard – bunch of grapes

**Comment by jessicagood** [comment]
@Lbookman Can you take responsibility for this one? I'm looking at the other posted issues.

**Comment by Lbookman** [comment]
i'll try to do it today but can't promise it will be done by tuesday @jessica-azgs @fmichaelconway

**Comment by Lbookman** [comment]
added icons with commit 832c94e @fmichaelconway can you fix the locations that don't have a type of business.

**Comment by skmar** [comment]
Hi @Lbookman and @jessica-azgs,

Is there a way to add the type of business field to the list of vineyards, http://winedb.arizonaexperience.org/admin/azwine/vineyard/, like Jessica did for the date established?
