### ISSUE TITLE
"More Detail" at Wine Map

### ISSUE THREAD

**Issue by fmichaelconway** [azgs/azwinemap#9]
Can we leapfrog the “More Detail” step and go directly to the account information?  There does not seem to be any good reason to make people click twice.  
At this stage, my chief concern is how much time it will take to streamline the coding?  
Jessica or Laura can you provide an estimate?

**Comment by jessicagood** [comment]
I looked at this some today. I think this will take significant time as the framework that was used for this application requires events to be bound to DOM elements and map markers aren't DOM elements. From help forums I've found it says that the entire view would have to be rewritten and the bindings done differently.

**Comment by ridavis** [comment]
I say it's not worth it. What say you @fmichaelconway?

**Comment by fmichaelconway** [comment]
Agreed. We will have to live with it.
